baseURL: https://jalcocert.github.io/
languageCode: en-us
title: Linuxz
theme: cupper-hugo-theme

params:
  description: An accessibility-friendly Hugo theme, ported from the [original Cupper](https://github.com/ThePacielloGroup/cupper) project.
  homeMetaContent: An accessibility-friendly Hugo theme, ported from the original Cupper project.
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Netlify](https://www.netlify.com/).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: JAlcocerT
  katex: true

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Debian Based
      url: /post/
      weight: 2
    - name: Arch Based
      url: /Arch/
      weight: 3
    - name: Tags
      url: /tags/
      weight: 4            
    - name: About
      url: /about/
      weight: 5          