baseURL: https://jalcocert.github.io/
languageCode: en-us
title: Linux
theme: cupper-hugo-theme

params:
  description: Linux OS's quick start guide for everyone.
  homeMetaContent: Linux OS's quick start guide for everyone.
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Github](https://github.com/JAlcocerT/Linux/).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: JAlcocerT
  katex: true

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Debian Based
      url: /Debian/
      weight: 2
    - name: Arch Based
      url: /Arch/
      weight: 3
    - name: Nix Package Manager
      url: /Nix/
      weight: 4          
    # - name: Tags
    #   url: /tags/
    #  weight: 4   
    - name: Linux & the Cloud
      url: /LinuxCloud/
      weight: 5            
    - name: About
      url: /about/
      weight: 6          