#!/bin/sh

sudo apt-get update
sudo apt dist-upgrade
 
#unnatended upgrades
sudo apt install unattended-upgrades
systemctl status unattended-upgrades

#firewall
sudo ss -tupln #ports in use
sudo apt install ufw #ufw
sudo ufw status
sudo ufw allow 717 #example to allow conexion
sudo ufw enable
sudo ufw status
sudo ufw reload #restart it

#ssh
sudo apt-get install openssh-server #verify that it is installed on the server
sudo enable ssh #enable it

sudo ssh root@192.168.1.31 #connecting to server from the client
sudo ssh-keygen #generating the keys, the public one has to be copied on the server
cat .ssh/id_rsa.pub
sudo nano .ssh/authorized_keys #and include it on the server
logout #logout from server and next time should not ask for any pass


sudo ssh root@192.168.1.31 #connecting again to check if the certificate worked
