#!/bin/sh
 
#Ubuntu tweaks & security
sudo apt-get install synaptic -y

##ppa GUI manager
sudo add-apt-repository ppa:webupd8team/y-ppa-manager
sudo apt-get update
sudo apt-get install y-ppa-manager -y

#check ppas
#ls /etc/apt/sources.list.d
#remove a specific ppa
#sudo rm -i /etc/apt/sources.list.d/google-chrome.list


sudo apt install unattended-upgrades -y
sudo dpkg-reconfigure -plow unattended-upgrades


 
### MEDIA ###

sudo apt install snapd

snap install spotify && snap install vlc

#Browsers
sudo snap install brave

distro=$(if echo " bullseye focal impish uma una " | grep -q " $(lsb_release -sc) "; then echo $(lsb_release -sc); else echo focal; fi)
echo "deb [arch=amd64] http://deb.librewolf.net $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/librewolf.list
sudo apt install wget -y
sudo wget https://deb.librewolf.net/keyring.gpg -O /etc/apt/trusted.gpg.d/librewolf.gpg
sudo apt update -y
sudo apt install librewolf -y

#chrome
#wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#sudo apt install ./google-chrome-stable_current_amd64.deb
#rm google-chrome-stable_current_amd64.deb

#Design
sudo snap install blender --classic && snap install freecad && snap install openscad && snap install cura-slicer 
sudo add-apt-repository ppa:kicad/kicad-5.1-releases && sudo apt update && sudo apt install kicad

sudo snap install shotcut -- classic && snap install gimp && snap install photoscape  && snap install inkscape

#https://github.com/upscayl/upscayl/releases
#sudo wget https://github.com/upscayl/upscayl/releases/download/v1.5.5/Upscayl-1.5.5.AppImage
#chmod +x ./*.AppImage

# Screen recording & audio
sudo apt install kazam #sharex foss for windows
sudo snap install audacity

sudo add-apt-repository ppa:openshot.developers/ppa
sudo apt-get update
sudo apt-get install openshot-qt

sudo add-apt-repository ppa:scribus/ppa
sudo apt update
sudo apt install scribus
#sudo apt remove scribus
#sudo add-apt-repository --remove ppa:scribus/ppa

######

### PROGRAMMING ###

#octave
sudo apt-get install flatpak
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub org.octave.Octave -y

sudo snap install slack --classic

sudo snap install code --classic
sudo snap install flutter --classic
sudo snap install android-studio --classic

sudo apt-get update
sudo apt-get upgrade
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
sudo apt install apt-transport-https
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
sudo apt update
sudo apt install sublime-text

sudo snap install notepad-plus-plus
sudo snap install atom --classic


#R
sudo apt -y install r-base
#wget https://download1.rstudio.org/desktop/bionic/amd64/rstudio-2022.02.2-485-amd64.deb
#sudo apt install ./rstudio-2021.09.2-382-amd64.deb

#github desktop
sudo wget https://github.com/shiftkey/desktop/releases/download/release-2.9.3-linux3/GitHubDesktop-linux-2.9.3-linux3.deb
sudo apt install ./GitHubDesktop-linux-2.9.3-linux3.deb
#sudo apt-get install gdebi-core 
#sudo gdebi GitHubDesktop-linux-2.9.3-linux3.deb -y

sudo snap install notepad-plus-plus

#RPi
sudo apt install rpi-imager

######

### GAMES ###

sudo snap install discord
sudo apt install anbox -y

#waydroid
sudo apt install curl ca-certificates -y
#export DISTRO="jammy"
sudo curl --proto '=https' --tlsv1.2 -Sf https://repo.waydro.id/waydroid.gpg --output /usr/share/keyrings/waydroid.gpg
echo "deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.id/ $DISTRO main" | sudo tee /etc/apt/sources.list.d/waydroid.list
sudo apt update
sudo apt install waydroid -y
sudo systemctl enable --now waydroid-container


#(AMD drivers to be installed here):
#https://github.com/lutris/docs/blob/master/InstallingDrivers.md
sudo add-apt-repository ppa:kisak/kisak-mesa
sudo dpkg --add-architecture i386 
sudo apt update && sudo apt upgrade -y
sudo apt install libgl1-mesa-dri:i386
sudo apt install mesa-vulkan-drivers mesa-vulkan-drivers:i386 -y


#Install Steam using the following Terminal command:
sudo apt install steam -y
#Once installed, run Steam, install any updates, and sign into your Steam account. 
#Enable Proton to work with all your Steam library by navigating to Steam / Steam Play / Advanced, and ticking the Enable Steam Play for all other titles.
#Reboot Steam once done

#STEP 4 - INSTALL WINE AND LUTRIS
#https://wine.htmlvalidator.com/install-wine-on-ubuntu-20.04.html
#https://linuxconfig.org/install-lutris-on-ubuntu-20-04-focal-fossa-linux


#https://github.com/lutris/docs/blob/master/Origin.md
sudo apt install libgnutls30:i386 libldap-2.4-2:i386 libgpg-error0:i386 libxml2:i386 libasound2-plugins:i386 libsdl2-2.0-0:i386 libfreetype6:i386 libdbus-1-3:i386 -y
sudo apt install wine -y

#https://lutris.net/downloads/
sudo add-apt-repository ppa:lutris-team/lutris
sudo apt update
sudo apt install lutris -y

#epic game store
#https://lutris.net/games/epic-games-store/

#origin

#gamebuntu
#https://gitlab.com/rswat09/gamebuntu/

######

### BACKUP ###
sudo apt-get install nautilus-dropbox -y

#megasync
#wget https://mega.nz/linux/MEGAsync/xUbuntu_20.04/amd64/megasync-xUbuntu_20.04_amd64.deb
#cd ~/Downloads
#sudo apt install ./megasync-xUbuntu_20.04_amd64.deb

#timeshift
sudo add-apt-repository ppa:teejee2008/ppa
sudo apt-get update
sudo apt-get install timeshift

#nextcloud
sudo add-apt-repository ppa:nextcloud-devs/client
sudo apt install nextcloud-client -y
#remember to add in: showExperimentalOptions=true
#the following line: /home/yourusername/.config/Nextloud

#Synkron
#sudo add-apt-repository ppa:rock-core/qt4
#sudo apt update
#http://synkron.sourceforge.net/download.php
#apt-get install build-essential libqt4-dev
#tar -xvf Synkron-1.6.2-src.tar.gz
#cd Synkron-1.6.2-src
#lrelease-qt4 Synkron.pro
#qmake-qt4 Synkron.pro
#make
#./synkron

#Grsync
sudo apt-get install grsync

######

###VBOX###
wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib"
sudo apt update && sudo apt install virtualbox-6.0 -y
sudo modprobe vboxdrv
#sudo apt remove virtualbox-dkms #if error on previous command
sudo apt install virtualbox-dkms -y

#vnc server
#vnc viewer
wget https://downloads.realvnc.com/download/file/viewer.files/VNC-Viewer-6.22.315-Linux-x86.deb
sudo apt install ./VNC-Viewer-6.22.315-Linux-x86.deb -y

######

### Productivity ###

sudo apt-get install gnome-shell-pomodoro
#Ulauncher #ctrl + space
#Flameshot
#kdenlive video editor

### Social ###

sudo apt install thunderbird
#telegram desktop
#cawbierd twitter client #chronological tweets
#feeds (rss client)



### SECURITY ###

#Firewall
#sudo ufw enable
sudo add-apt-repository universe 
sudo apt update -y
sudo apt install gufw -y


#VPN
sudo apt-get install apt-transport-https &&
curl -fsSL https://pkgs.tailscale.com/stable/raspbian/buster.gpg | sudo apt-key add - &&
curl -fsSL https://pkgs.tailscale.com/stable/raspbian/buster.list | sudo tee /etc/apt/sources.list.d/tailscale.list &&
sudo apt-get update &&
sudo apt-get install tailscale &&
sudo tailscale up &&
tailscale ip -4
#ssh user_name@ip_given_from_tailscale ---> will connect to the device

#echo 'net.ipv4.ip_forward = 1' | sudo tee -a /etc/sysctl.conf &&
#echo 'net.ipv6.conf.all.forwarding = 1' | sudo tee -a /etc/sysctl.conf &&
#sudo sysctl -p /etc/sysctl.conf &&
#sudo tailscale down

#sudo tailscale up --advertise-exit-node
sudo tailscale up --exit-node=ip.add.re.ss --advertise-exit-node  #action needed on this exit node after its validation on the web console -> settings/edit route settings

#Password managers & 2FA's

sudo snap install bitwarden
sudo add-apt-repository ppa:phoerious/keepassxc #offline password manager
sudo apt update && sudo apt install keepassxc
#sudo add-apt-repository --remove ppa:phoerious/keepassxc
#sudo apt remove --autoremove keepassxc

sudo apt-get install aegis
sudo snap install authy

#mac
#sudo apt-get install macchanger

#element client
sudo apt install -y wget apt-transport-https
‍sudo wget -O /usr/share/keyrings/element-io-archive-keyring.gpg https://packages.element.io/debian/element-io-archive-keyring.gpg
‍echo "deb [signed-by=/usr/share/keyrings/element-io-archive-keyring.gpg] https://packages.element.io/debian/ default main" | sudo tee /etc/apt/sources.list.d/element-io.list
sudo apt update
sudo apt install element-desktop

######



##### OTHERS #####

#Unetbootin
#https://unetbootin.github.io/linux_download.html
sudo add-apt-repository ppa:gezakovacs/ppa
sudo apt-get update
sudo apt-get install unetbootin

##WIFI DRIVERS (example dkms)
sudo apt-get update
sudo apt-get install dkms

#https://github.com/cilynx/rtl88x2bu
git clone https://github.com/cilynx/rtl88x2bu.git
cd rtl88x2bu
VER=$(sed -n 's/\PACKAGE_VERSION="\(.*\)"/\1/p' dkms.conf)
sudo rsync -rvhP ./ /usr/src/rtl88x2bu-${VER}
sudo dkms add -m rtl88x2bu -v ${VER}
sudo dkms build -m rtl88x2bu -v ${VER}
sudo dkms install -m rtl88x2bu -v ${VER}
sudo modprobe 88x2bu
#rm GitHubDesktop-linux-2.9.3-linux3.deb

#eid #https://github.com/open-eid/DigiDoc4-Client#ubuntu
#https://installer.id.ee/media/install-scripts/install-open-eid.sh
#chmod +x ./install-open-eid.sh
#./install-open-eid.sh

### LAPTOP ### 

#sudo snap install auto-cpufreq

#Cambiar teclado
#sudo apt-get install console-data
#sudo setxkbmap -layout 'es,es' -model pc105

###### ######
