#!/bin/sh
 
#Ubuntu tweaks
sudo apt-get install synaptic
 
#Media
snap install spotify && snap install vlc

#Design
sudo snap install blender --classic && snap install freecad && snap install openscad && snap install cura-slicer 
sudo snap install shotcut -- classic && snap install gimp && snap install photoscape  && snap install inkscape
sudo add-apt-repository ppa:kicad/kicad-5.1-releases && sudo apt update && sudo apt install kicad


#Games
sudo apt install steam -y
sudo snap install discord
sudo apt install anbox -y

#Storage:
sudo apt-get install nautilus-dropbox
wget https://mega.nz/linux/MEGAsync/xUbuntu_20.04/amd64/megasync-xUbuntu_20.04_amd64.deb
cd ~/Downloads
sudo apt install ./megasync-xUbuntu_20.04_amd64.deb

#VBox
wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib"
sudo apt update && sudo apt install virtualbox-6.0 -y
sudo modprobe vboxdrv
#sudo apt remove virtualbox-dkms #if error on previous command
sudo apt install virtualbox-dkms -y
