#!/bin/sh
 
#Ubuntu tweaks
sudo apt-get install synaptic
 
#Media
snap install spotify && snap install vlc

#Design
sudo snap install blender --classic && snap install freecad && snap install openscad && snap install cura-slicer 
sudo snap install shotcut -- classic && snap install gimp && snap install photoscape  && snap install inkscape
sudo add-apt-repository ppa:kicad/kicad-5.1-releases && sudo apt update && sudo apt install kicad


#Games

sudo snap install discord
sudo apt install anbox -y


#(AMD drivers to be installed here):
#https://github.com/lutris/docs/blob/master/InstallingDrivers.md
sudo add-apt-repository ppa:kisak/kisak-mesa
sudo dpkg --add-architecture i386 
sudo apt update && sudo apt upgrade
sudo apt install libgl1-mesa-dri:i386
sudo apt install mesa-vulkan-drivers mesa-vulkan-drivers:i386


#Install Steam using the following Terminal command:
sudo apt install steam -y
#Once installed, run Steam, install any updates, and sign into your Steam account. 
#Enable Proton to work with all your Steam library by navigating to Steam / Steam Play / Advanced, and ticking the Enable Steam Play for all other titles.
#Reboot Steam once done
#STEP 4 - INSTALL WINE AND LUTRIS
https://wine.htmlvalidator.com/install-wine-on-ubuntu-20.04.html
https://linuxconfig.org/install-lutris-on-ubuntu-20-04-focal-fossa-linux


#Storage:
sudo apt-get install nautilus-dropbox
wget https://mega.nz/linux/MEGAsync/xUbuntu_20.04/amd64/megasync-xUbuntu_20.04_amd64.deb
cd ~/Downloads
sudo apt install ./megasync-xUbuntu_20.04_amd64.deb

#VBox
wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib"
sudo apt update && sudo apt install virtualbox-6.0 -y
sudo modprobe vboxdrv
#sudo apt remove virtualbox-dkms #if error on previous command
sudo apt install virtualbox-dkms -y
