---
- name: Master Playbook RPi
  hosts: localhost
  gather_facts: no
  become: yes
  vars:
    username: reisipi  # Replace with your username  
  tasks:

    - name: Ensure the destination directory exists - Wireguard
      file:
        path: "/home/{{ username }}/Docker/Wireguard"
        state: directory
        mode: '0755'
      become_user: "{{ username }}"  
   - name: Download wireguard_docker-compose.yml from GitHub
      get_url:
        url: https://raw.githubusercontent.com/JAlcocerT/Docker/main/Security/wireguard_docker-compose.yml
        dest: /home/{{ username }}/Docker/Wireguard/docker-compose.yml
        mode: '0755'
    - name: Deploy with Docker Compose - Wireguard
      docker_compose:
        project_src: /home/{{ username }}/Docker/Wireguard
        state: present      

    - name: Ensure the destination directory exists - uptimekuma
      file:
        path: "/home/{{ username }}/Docker/uptimekuma"
        state: directory
        mode: '0755'
      become_user: "{{ username }}"  
   - name: Download uptimekuma_docker-compose.yml from GitHub
      get_url:
        url: https://raw.githubusercontent.com/JAlcocerT/Docker/main/Security/uptimekuma_docker-compose.yml
        dest: /home/{{ username }}/Docker/uptimekuma/docker-compose.yml
        mode: '0755'
    - name: Deploy with Docker Compose - uptimekuma
      docker_compose:
        project_src: /home/{{ username }}/Docker/uptimekuma
        state: present     

    - name: Ensure the destination directory exists - NetData
      file:
        path: "/home/{{ username }}/Docker/NetData"
        state: directory
        mode: '0755'
      become_user: "{{ username }}"  
   - name: Download NetData_docker-compose.yml from GitHub
      get_url:
        url: https://raw.githubusercontent.com/JAlcocerT/Docker/main/IoT/NetData_docker-compose.yaml
        dest: /home/{{ username }}/Docker/NetData/docker-compose.yml
        mode: '0755'
    - name: Deploy with Docker Compose - NetData
      docker_compose:
        project_src: /home/{{ username }}/Docker/NetData
        state: present    

        #sudo docker run -d -p 8000:8000 -p 9000:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce
                 

# sudo docker exec -it your_gluetun_container_name sh
# wget -qO- https://ipinfo.io/json #the command to use
# sudo docker exec your_gluetun_container_name wget -qO- https://ipinfo.io/json
# curl https://am.i.mullvad.net/json
# apt installed wireguard
# cp /home/reisipi/Downloads/pl-waw-wg-101.conf /etc/wireguard
# sudo wg-quick up your_vpn_wireguard_configuration #the name of the .conf file that you have downloaded (without .conf)

# version: "3"
# services:
#   gluetun:
#     image: qmcgaw/gluetun
#     container_name: your_gluetun_container_name    
#     cap_add:
#       - NET_ADMIN
#     ports: #make sure to include these for qbittorrent to work
#       - 51820:51820
#       # - 6081:6881/udp
#       # - 6011:6011      
#     environment:
#       - VPN_SERVICE_PROVIDER=mullvad
#       - VPN_TYPE=wireguard
#       - WIREGUARD_PRIVATE_KEY=yourkey
#       - WIREGUARD_ADDRESSES=theip/something
#       - SERVER_CITIES=New York NY #choose any available city
#     volumes:
#       - /home/Docker/Gluetun:/gluetun
#     restart: unless-stopped

# sudo ansible-playbook rpi-essentials_ansible-playbook.yml -e "username=reisipi"


    # - name: Include VSCodium Playbook
    #   include: ../Ansible/install_dev_vscodium.yml

    # - name: Include Python Playbook
    #   include: ../Ansible/install_dev_python.yml

    # - name: Include Docker Playbook
    #   include: ../Ansible/install_docker.yml      

    # - name: Include the specific task from another folder
    #   include_tasks: ../Ansible/install_linux_tools.yml
    #   tasks_from: #Install sysbench
    #     - Install Gufw (Firewall Configuration Tool)
    #     - Install sysbench

#https://registry.hub.docker.com/r/jokobsk/pi.alert        

    # - name: Include the specific task from example.yml
    #   include_tasks: example.yml
    #   tasks_from: my_task.yml      

    # - name: Include Other Playbook
    #   include: other_example.yml


    #sudo ansible-playbook rpi-essentials_ansible-playbook.yml
    #sudo ansible-playbook rpi-essentials_ansible-playbook.yml -e "username=reisipi"
