#!/bin/sh
 
#Ubuntu tweaks & security
sudo apt-get install synaptic -y

##ppa GUI manager
sudo add-apt-repository ppa:webupd8team/y-ppa-manager
sudo apt-get update
sudo apt-get install y-ppa-manager -y

#check ppas
#ls /etc/apt/sources.list.d
#remove a specific ppa
#sudo rm -i /etc/apt/sources.list.d/google-chrome.list


sudo apt install unattended-upgrades -y
sudo dpkg-reconfigure -plow unattended-upgrades

### Docker ###

#curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
#sh /tmp/get-docker.sh


### Podman ###



################################
### Package Managent Systems ###
################################

#sudo apt update
#sudo apt install snapd #https://snapcraft.io/store

#sudo apt-get install flatpak #https://flathub.org/en

#curl -L https://nixos.org/nix/install | sh #https://search.nixos.org/packages?
#sudo bash ./nix-*-multi-user.sh

#nala

#############
### MEDIA ###
#############


sudo apt install snapd

#snap install spotify
snap install vlc

#flatpak install flathub io.freetubeapp.FreeTube

#Browsers
sudo snap install brave
flatpak install flathub com.github.micahflee.torbrowser-launcher

#librewolf
distro=$(if echo " bullseye focal impish uma una " | grep -q " $(lsb_release -sc) "; then echo $(lsb_release -sc); else echo focal; fi)
echo "deb [arch=amd64] http://deb.librewolf.net $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/librewolf.list
sudo apt install wget -y
sudo wget https://deb.librewolf.net/keyring.gpg -O /etc/apt/trusted.gpg.d/librewolf.gpg
sudo apt update -y
sudo apt install librewolf -y

#chrome
#wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#sudo apt install ./google-chrome-stable_current_amd64.deb
#rm google-chrome-stable_current_amd64.deb
#chromium


##############
### Design ###
##############

sudo snap install gimp


#sudo snap install upscayl
#flatpak install flathub org.upscayl.Upscayl
#https://github.com/upscayl/upscayl/releases
#sudo wget https://github.com/upscayl/upscayl/releases/download/v1.5.5/Upscayl-1.5.5.AppImage
#chmod +x ./*.AppImage


sudo snap install blender --classic && snap install freecad && snap install openscad && snap install cura-slicer 

sudo snap install shotcut -- classic && snap install photoscape  && snap install inkscape

sudo snap install penpot-desktop


#Flameshot
#kdenlive video editor
#openshot
#sudo snap install shotcut --classic


# Screen recording & audio
sudo apt install kazam #sharex foss for windows
sudo snap install audacity

sudo add-apt-repository ppa:openshot.developers/ppa
sudo apt-get update
sudo apt-get install openshot-qt

#E-Book Design
sudo add-apt-repository ppa:scribus/ppa
sudo apt update
sudo apt install scribus
#sudo apt remove scribus
#sudo add-apt-repository --remove ppa:scribus/ppa




###################
### PROGRAMMING ###
###################


#https://snapcraft.io/docs/python-apps

#Octave (GPL v3)
#sudo apt-get install flatpak
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub org.octave.Octave -y


#sudo snap install code --classic

#sudo snap install codium --classic
nix-env -iA nixpkgs.vscodium

sudo snap install flutter --classic
sudo snap install android-studio --classic

#Sublime (Not OSS)
#sudo apt-get update
#sudo apt-get upgrade
#wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
#sudo apt install apt-transport-https
#echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
#sudo apt update
#sudo apt install sublime-text

sudo snap install notepad-plus-plus #(GPL v2)
sudo snap install atom --classic #(MIT)


#R & Rstudio(GPL)
sudo apt -y install r-base #https://cran.rstudio.com/
#wget https://download1.rstudio.org/desktop/bionic/amd64/rstudio-2022.02.2-485-amd64.deb
#sudo apt install ./rstudio-2021.09.2-382-amd64.deb


#KNIME (GPL)

# wget -O knime.tar.gz https://download.knime.org/analytics-platform/linux/knime-latest51-linux.gtk.x86_64.tar.gz
# tar -xvzf knime.tar.gz
# sudo mv knime_* /opt/knime
# # Create a symbolic link (optional, for easier execution)
# sudo ln -s /opt/knime/knime /usr/local/bin/knime
# # Run KNIME (you can now run it using 'knime' command)
# knime

#Github Desktop:
#sudo wget https://github.com/shiftkey/desktop/releases/download/release-2.9.3-linux3/GitHubDesktop-linux-2.9.3-linux3.deb
#sudo apt install ./GitHubDesktop-linux-2.9.3-linux3.deb
#sudo apt-get install gdebi-core 
#sudo gdebi GitHubDesktop-linux-2.9.3-linux3.deb -y
#To get the latest Automatically
# curl -s https://api.github.com/repos/shiftkey/desktop/releases/latest \
# | grep "GitHubDesktop-linux-.*deb" \
# | cut -d : -f 2,3 \
# | tr -d \" \
# | wget -qi -
# sudo apt install ./GitHubDesktop-linux-*.deb




###########
### IoT ###
###########

#RPi
sudo apt install rpi-imager

sudo snap install mosquitto
sudo snap install node-red

sudo snap install openhab

#Electronics
sudo add-apt-repository ppa:kicad/kicad-5.1-releases && sudo apt update && sudo apt install kicad


#############
### GAMES ###
#############

sudo apt install anbox -y

#waydroid
sudo apt install curl ca-certificates -y
#export DISTRO="jammy"
sudo curl --proto '=https' --tlsv1.2 -Sf https://repo.waydro.id/waydroid.gpg --output /usr/share/keyrings/waydroid.gpg
echo "deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.id/ $DISTRO main" | sudo tee /etc/apt/sources.list.d/waydroid.list
sudo apt update
sudo apt install waydroid -y
sudo systemctl enable --now waydroid-container


#(AMD drivers to be installed here):
#https://github.com/lutris/docs/blob/master/InstallingDrivers.md
sudo add-apt-repository ppa:kisak/kisak-mesa
sudo dpkg --add-architecture i386 
sudo apt update && sudo apt upgrade -y
sudo apt install libgl1-mesa-dri:i386
sudo apt install mesa-vulkan-drivers mesa-vulkan-drivers:i386 -y


#Install STEAM using the following Terminal command:
#sudo apt install steam -y
#Once installed, run Steam, install any updates, and sign into your Steam account. 
#Enable Proton to work with all your Steam library by navigating to Steam / Settings / Steam Play / Advanced, and ticking the Enable Steam Play for all other titles.
#Reboot Steam once done

#STEP 4 - INSTALL WINE AND LUTRIS
#https://wine.htmlvalidator.com/install-wine-on-ubuntu-20.04.html
#https://linuxconfig.org/install-lutris-on-ubuntu-20-04-focal-fossa-linux


#https://github.com/lutris/docs/blob/master/Origin.md
sudo apt install libgnutls30:i386 libldap-2.4-2:i386 libgpg-error0:i386 libxml2:i386 libasound2-plugins:i386 libsdl2-2.0-0:i386 libfreetype6:i386 libdbus-1-3:i386 -y
sudo apt install wine -y

#https://lutris.net/downloads/
sudo add-apt-repository ppa:lutris-team/lutris
sudo apt update
sudo apt install lutris -y

#epic game store
#https://lutris.net/games/epic-games-store/

#origin

#gamebuntu
#https://gitlab.com/rswat09/gamebuntu/


###############
### BACKUPS ###
###############

#dropbox
#sudo apt-get install nautilus-dropbox -y

#megasync
#wget https://mega.nz/linux/MEGAsync/xUbuntu_20.04/amd64/megasync-xUbuntu_20.04_amd64.deb
#cd ~/Downloads
#sudo apt install ./megasync-xUbuntu_20.04_amd64.deb

#timeshift
sudo add-apt-repository ppa:teejee2008/ppa
sudo apt-get update
sudo apt-get install timeshift

#nextcloud
flatpak install flathub com.nextcloud.desktopclient.nextcloud
# sudo add-apt-repository ppa:nextcloud-devs/client
# sudo apt install nextcloud-client -y
#remember to add in: showExperimentalOptions=true
#the following line: /home/yourusername/.config/Nextloud

#Synkron
#sudo add-apt-repository ppa:rock-core/qt4
#sudo apt update
#http://synkron.sourceforge.net/download.php
#apt-get install build-essential libqt4-dev
#tar -xvf Synkron-1.6.2-src.tar.gz
#cd Synkron-1.6.2-src
#lrelease-qt4 Synkron.pro
#qmake-qt4 Synkron.pro
#make
#./synkron

#Grsync
sudo apt-get install grsync

######

###VBOX###
wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib"
sudo apt update && sudo apt install virtualbox-6.0 -y
sudo modprobe vboxdrv
#sudo apt remove virtualbox-dkms #if error on previous command
sudo apt install virtualbox-dkms -y

#vnc server
#vnc viewer
wget https://downloads.realvnc.com/download/file/viewer.files/VNC-Viewer-6.22.315-Linux-x86.deb
sudo apt install ./VNC-Viewer-6.22.315-Linux-x86.deb -y


####################
### Productivity ###
####################

sudo apt-get install gnome-shell-pomodoro
#Ulauncher #ctrl + space

sudo snap install wekan
sudo snap install libreoffice
sudo snap install drawio


#flatpak install flathub md.obsidian.Obsidian
flatpak install flathub com.github.zadam.trilium
flatpak install flathub net.cozic.joplin_desktop
flatpak install flathub com.logseq.Logseq

#notion vs appflowy
#https://github.com/AppFlowy-IO/appflowy

#https://github.com/mattermost/mattermost


##############
### Social ###
##############

sudo apt install thunderbird


# sudo snap install slack --classic
sudo snap install mattermost-desktop


# sudo snap install discord
flatpak install flathub chat.revolt.RevoltDesktop
#flatpak run chat.revolt.RevoltDesktop


#telegram desktop
#sudo apt install telegram-desktop
sudo snap install signal-desktop


#matrix client - element
sudo apt install apt-transport-https
sudo wget -O /usr/share/keyrings/element-io-archive-keyring.gpg https://packages.element.io/debian/element-io-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/element-io-archive-keyring.gpg] https://packages.element.io/debian/ default main" | sudo tee /etc/apt/sources.list.d/element-io.list
sudo apt update
sudo apt install element-desktop

#matrix client - fluffychat
sudo snap install fluffychat

#mastodon client
sudo snap install sengi

#nostr
#pixelfed
#https://pixelfed.org/



#cawbird twitter client #chronological tweets
sudo snap install cawbird
#feeds (rss client)


################
### SECURITY ###
################

#Firewall
#sudo ufw enable
sudo add-apt-repository universe 
sudo apt update -y
sudo apt install gufw -y


#VPNs

#https://github.com/tailscale/tailscale
# sudo apt-get install apt-transport-https &&
# curl -fsSL https://pkgs.tailscale.com/stable/raspbian/buster.gpg | sudo apt-key add - &&
# curl -fsSL https://pkgs.tailscale.com/stable/raspbian/buster.list | sudo tee /etc/apt/sources.list.d/tailscale.list &&
# sudo apt-get update &&
# sudo apt-get install tailscale &&
curl -fsSL https://tailscale.com/install.sh | sh
sudo tailscale up
#tailscale ip -4
#ssh user_name@ip_given_from_tailscale ---> will connect to the device

#echo 'net.ipv4.ip_forward = 1' | sudo tee -a /etc/sysctl.conf &&
#echo 'net.ipv6.conf.all.forwarding = 1' | sudo tee -a /etc/sysctl.conf &&
#sudo sysctl -p /etc/sysctl.conf &&
#sudo tailscale down

#sudo tailscale up --advertise-exit-node
#sudo tailscale up --exit-node=ip.add.re.ss --advertise-exit-node  #action needed on this exit node after its validation on the web console -> settings/edit route settings


wget --content-disposition https://mullvad.net/en/download/app/deb/latest
sudo apt install -y ./Mullvad*


#Password managers & 2FA's

sudo snap install bitwarden

sudo add-apt-repository ppa:phoerious/keepassxc #offline password manager
sudo apt update && sudo apt install keepassxc
#sudo add-apt-repository --remove ppa:phoerious/keepassxc
#sudo apt remove --autoremove keepassxc

sudo apt-get install aegis
#sudo snap install authy

#mac
#sudo apt-get install macchanger

##################
##### FINANCE ####
##################

flatpak install flathub info.portfolio_performance.PortfolioPerformance
flatpak run info.portfolio_performance.PortfolioPerformance

sudo add-apt-repository ppa:mdoyen/homebank
sudo apt-get update
sudo apt-get install homebank

#crypto
#nix-env -iA nixpkgs.electrum
#flatpak install flathub org.featherwallet.Feather

##################
##### OTHERS #####
##################

#Unetbootin
#https://unetbootin.github.io/linux_download.html
sudo add-apt-repository ppa:gezakovacs/ppa
sudo apt-get update
sudo apt-get install unetbootin

##WIFI DRIVERS (example dkms)
sudo apt-get update
sudo apt-get install dkms

#https://github.com/cilynx/rtl88x2bu
git clone https://github.com/cilynx/rtl88x2bu.git
cd rtl88x2bu
VER=$(sed -n 's/\PACKAGE_VERSION="\(.*\)"/\1/p' dkms.conf)
sudo rsync -rvhP ./ /usr/src/rtl88x2bu-${VER}
sudo dkms add -m rtl88x2bu -v ${VER}
sudo dkms build -m rtl88x2bu -v ${VER}
sudo dkms install -m rtl88x2bu -v ${VER}
sudo modprobe 88x2bu
#rm GitHubDesktop-linux-2.9.3-linux3.deb

##########################
### Buziness, Buziness ###
##########################

#EE
#eid #https://github.com/open-eid/DigiDoc4-Client#ubuntu
#https://installer.id.ee/media/install-scripts/install-open-eid.sh
#chmod +x ./install-open-eid.sh
#./install-open-eid.sh


##############
### TRAVEL ###
##############

flatpak install flathub app.organicmaps.desktop

##############
### LAPTOP ### 
##############

#sudo snap install auto-cpufreq

#change keyboard
#sudo apt-get install console-data
#sudo setxkbmap -layout 'es,es' -model pc105


####################
### Local Gen-AI ###
####################

#https://github.com/steven2358/awesome-generative-ai

#Vicuna-7B locally with CPU: https://fossengineer.com/Generative-AI-LLMs-locally-with-cpu/
#https://hub.docker.com/repository/docker/fossengineer/oobabooga_cpu/tags?page=1&ordering=last_updated
#docker pull fossengineer/oobabooga_cpu:latest
#wget https://huggingface.co/eachadea/ggml-vicuna-7b-1.1/resolve/main/ggml-old-vic7b-uncensored-q5_1.bin
#wget https://huggingface.co/eachadea/ggml-vicuna-7b-1.1/resolve/main/ggml-old-vic7b-uncensored-q5_1.bin -O /home/jalcocert/AI/Models/ggml-old-vic7b-uncensored-q5_1.bin


# version: '3'

# services:
#   genai_text:
#     image: fossengineer/oobabooga_cpu
#     container_name: genai_ooba_cpu
#     ports:
#       - "7860:7860"
#     working_dir: /app
#     command: tail -f /dev/null #keep it running
#     volumes:
#       - /home/jalcocert/AI/Models:/app/text-generation-webui/models