---
- name: Install Dart on Ubuntu
  hosts: localhost
  become: yes
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        state: present

    - name: Add Dart GPG key
      shell: |
        wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/dart.gpg
      args:
        executable: /bin/bash

    - name: Add Dart APT repository
      shell: |
        echo 'deb [signed-by=/usr/share/keyrings/dart.gpg arch=amd64] https://storage.googleapis.com/download.dartlang.org/linux/debian stable main' | sudo tee /etc/apt/sources.list.d/dart_stable.list
      args:
        executable: /bin/bash

    - name: Update APT cache (again)
      apt:
        update_cache: yes

    - name: Install Dart
      apt:
        name: dart
        state: present


#https://dart.dev/get-dart  
#sudo ansible-playbook install_dev_dart.yml
#dart --version
