---
- name: Install Docker on Ubuntu's
  hosts: localhost
  become: yes
  vars:
    username: jalcocert  # Replace with your username
  tasks:
    - name: Download and install Docker
      shell: |
        curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
        sh /tmp/get-docker.sh

    - name: Install docker-compose
      apt:
        name: docker-compose
        state: present
        update_cache: yes

    - name: Run Portainer Docker container
      docker_container:
        name: portainer
        image: portainer/portainer-ce
        ports:
          - "8000:8000"
          - "9000:9000"
        restart_policy: always
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data

#IoT - HomeAssistant


#Torrent & VPN

#https://jalcocert.github.io/RPi/posts/selfh-internet-better/

* PiHole + PiAlert + UnboundDNS + SearXNG

#https://jalcocert.github.io/RPi/posts/selfhosting-nextcloud/


#Photos - PiGallery