---
- name: Install R and RStudio on Ubuntu
  hosts: localhost
  become: yes
  tasks:
    - name: Install R base package
      apt:
        name: r-base
        state: present
        update_cache: yes

    - name: Download RStudio .deb package
      get_url:
        url: "https://download1.rstudio.org/electron/focal/amd64/rstudio-2023.06.2-561-amd64.deb"
        dest: "/tmp/rstudio-2023.06.2-561-amd64.deb"
        mode: '0644'

    - name: Install RStudio
      apt:
        deb: "/tmp/rstudio-2023.06.2-561-amd64.deb"


#ansible-playbook install_r_and_rstudio.yml -i localhost