---
- name: Install OBS Studio on Ubuntu
  hosts: localhost
  become: yes
  tasks:
    - name: Add OBS Studio APT repository
      apt_repository:
        repo: ppa:obsproject/obs-studio
        state: present

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install OBS Studio
      apt:
        name: obs-studio
        state: present


#sudo ansible-playbook install_obs.yml
