---
- name: Install Julia on Ubuntu
  hosts: localhost
  become: yes

  tasks:
    - name: Add the Julia PPA
      apt_repository:
        repo: 'ppa:deadsnakes/ppa'
        state: present

    - name: Install Julia
      apt:
        name: julia
        state: present
        update_cache: yes


#ansible-playbook install_dev_julia.yml -i localhost
