---
- name: Install Waydroid on Ubuntu
  hosts: localhost
  become: yes
  tasks:
    - name: Install curl and ca-certificates
      apt:
        name: [curl, ca-certificates]
        state: present

    - name: Download Waydroid GPG key
      shell: |
        sudo curl --proto '=https' --tlsv1.2 -Sf https://repo.waydro.id/waydroid.gpg --output /usr/share/keyrings/waydroid.gpg
      args:
        executable: /bin/bash

    - name: Add Waydroid APT repository
      shell: |
        echo "deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.id/ $DISTRO main" | sudo tee /etc/apt/sources.list.d/waydroid.list
      args:
        executable: /bin/bash

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Waydroid
      apt:
        name: waydroid
        state: present

    - name: Enable and start Waydroid service
      systemd:
        name: waydroid-container
        enabled: yes
        state: started


#sudo ansible-playbook install_waydroid.yml
