---
- name: Install Waydroid on Ubuntu
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure software-properties-common is installed
      apt:
        name: software-properties-common
        state: present

    - name: Add Waydroid repository
      apt_repository:
        repo: 'ppa:waydroid/waydroid'
        state: present
      register: repo_added

    - name: Update APT cache if repo was added
      apt:
        update_cache: yes
      when: repo_added.changed

    - name: Install Waydroid and related packages
      apt:
        name:
          - waydroid
          - waydroid-images
        state: present

    - name: Initialize Waydroid (This may take a while)
      command: waydroid init
      args:
        creates: /var/lib/waydroid/images/system.img

##sudo ansible-playbook install_waydroid.yml