---
- name: Install Python 3.9 on Ubuntu
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure software-properties-common is installed (to use add-apt-repository)
      apt:
        name: software-properties-common
        state: present

    - name: Add deadsnakes PPA
      apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present

    - name: Install Python 3.9
      apt:
        name:
          - python3.9
          - python3.9-venv
          - python3.9-dev
        state: present
        update_cache: yes

    - name: Get Python 3.9 version
      command: python3.9 --version
      register: python_version
      changed_when: false  # This ensures Ansible doesn't mark this as a "change"

    - name: Display Python 3.9 version
      debug:
        msg: "Installed Python Version: {{ python_version.stdout }}"

#sudo ansible-playbook install_python.yml